"""Added all tables and relations

Revision ID: 5f7edab99eb9
Revises: ffdc0a98111c
Create Date: 2021-03-03 11:58:29.053107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7edab99eb9'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('priceInC', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input1Id', sa.Integer(), nullable=False),
    sa.Column('input1Quantity', sa.Integer(), nullable=False),
    sa.Column('input2Id', sa.Integer(), nullable=True),
    sa.Column('input2Quantity', sa.Integer(), nullable=True),
    sa.Column('outputId', sa.Integer(), nullable=False),
    sa.Column('outputQuantity', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('profit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['input1Id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['input2Id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['outputId'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flipId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['flipId'], ['flips.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flipId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flipId'], ['flips.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('flips')
    op.drop_table('items')
    # ### end Alembic commands ###
